# NumPy

NumPy是一个功能强大的Python库，主要用于对多维数组执行计算



In [10]:
import numpy as np

data = [1,2,3,4,5]
x = np.array(data)
print(x)

[1 2 3 4 5]


In [2]:
#创建一个长度为5的NumPy数组，但所有元素都为0

import numpy as np
x = np.zeros((5))
print(x)

[0. 0. 0. 0. 0.]


In [7]:
#创建随机数组

import numpy as np
x = np.random.random((6))
print(x)

[0.79212614 0.17780418 0.04449092 0.75020897 0.73386741 0.87568303]


### 数组操作

创建数组的四个方式

In [14]:
import numpy as np

a = np.array([1,2,3])
print(a)

b = np.array((0,5,6,8))
print(b)

c = np.arange(6)
print(c)

d = np.linspace(0,np.pi,5)
print(d)

print(np.pi)

[1 2 3]
[0 5 6 8]
[0 1 2 3 4 5]
[0.         0.78539816 1.57079633 2.35619449 3.14159265]
3.141592653589793


In [19]:
import numpy as np


a = np.array([1,2,3])
b = np.array([4,1,6])

print(a+b)
print(a*b)
print(a>b)


[5 3 9]
[ 4  2 18]
[False  True False]


In [20]:
import numpy as np

a = np.array([[1,2,3],[7,8,9]])
b = 10
print(a*b)

print("\n\n",a,type(a))

[[10 20 30]
 [70 80 90]]


 [[1 2 3]
 [7 8 9]] <class 'numpy.ndarray'>


### 特殊运算

In [25]:
import numpy as np

a = np.arange(10)
print(a)

print(a.sum())
print(a.min())
print(a.max())
print(a.cumsum())

[0 1 2 3 4 5 6 7 8 9]
45
0
9
[ 0  1  3  6 10 15 21 28 36 45]


### 索引

In [29]:
import numpy as np

a = np.arange(0,100,5)

b = a[[1,3,5,7,9]]  #索引为1 3 5 7 9的数据

print(a)
print(b)

[ 0  5 10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95]
[ 5 15 25 35 45]


In [33]:
import numpy as np

a = np.arange(0,100,5)

b = a[a>=50]
print(b)

c = a[:5] #获取a[0,5)
print(c)

[50 55 60 65 70 75 80 85 90 95]
[ 0  5 10 15 20]


### Where 函数

where() 函数是另外一个根据条件返回数组中的值的有效方法。只需要把条件传递给它，它就会返回一个使得条件为真的元素的列表。

In [40]:
import numpy as np

a = np.arange(0,100,5)

b = np.where(a>50)[0]
print(a,"\n",b)

[ 0  5 10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95] 
 [11 12 13 14 15 16 17 18 19]
